#!/bin/sh

/bin/rm index.tar.gz latest-versions
/bin/rm -rf archives downloads unpack
mkdir archives downloads unpack
/bin/rm -f tmp/*
/bin/rm -f all-hs-files lex-test-exe lex-test-report
/bin/rm -f not-ok-files report-default report-single report-unicode

